### PR TITLE
Refactor Claim and EntityDeserializer

### PR DESCRIPTION
**Pull request by thiemowmde**
Please look at the ~~4~~ 3 commits independently and tell me which are ok for you. I will remove the ones you are not ok with. Or you can just merge all of them. ;-)

### CODE REVIEW

**Comment by thiemowmde** [comment]
Rebased.

**Comment by addshore** [comment]
Needs another rebase :/

**Comment by thiemowmde** [comment]
Rebased again.

**Comment by Benestar** [comment]
First I thought this wouldn't really change anything but if I think about it, most entities should be serialized using the current serialization now so this might actually be a performance improvement.

**Pull request merged**
