### PR TITLE
Use extension registration for MediaWiki credits

### PR DESCRIPTION
**Pull request by filbertkm**
this also fixes the broken license link on Special:Version

### CODE REVIEW

**Comment by JeroenDeDauw** [comment]
If possible, I think it'd be nice to have this file be named `mediawiki.json` rather than `extension.json`, so it's more clear what it is about.

**Comment by mariushoch** [comment]
Not possible AFAIK. Could probably be done by linking extension.json to mediawiki.json, though… not sure I like that approach, though.

**Comment by JeroenDeDauw** [comment]
Why not possible? The path is included in the call to wfLoadExtension. Will something fail if you pass in a path that is not `extension.json` (then why is this even a thing you pass in)?

**Comment by filbertkm** [comment]
possibly mediawiki.json might work, but I think extension.json is more clear + consistent. This is what it is typically (always) called elsewhere and is what people would search + look for.

we explicitly provide the path because these libraries typically are installed in a non-standard extension location.

**Comment by JeroenDeDauw** [comment]
> but I think extension.json is more clear + consistent. This is what it is typically (always) called elsewhere and is what people would search + look for.

I was somewhat expecting that argument and certainly understand where it's coming from. However please consider that this is not a MediaWiki extension. To me it makes a lot more sense to make the layout as clear as possible viewing it as a PHP library as opposed to a MediaWiki extension, since it is a PHP library. The only reason this stuff is even there is to have the library version show up on Special:Version when it is used by MediaWiki.

**Comment by mariushoch** [comment]
As we need to give full paths for deploying with the build anyway, it would be ok for me to use `mediawiki.json`, although I can certainly see the argument for sticking with the default.

Maybe we should make the extension registration also look for `mediawiki.json` for cases like this? If we were to do that renaming would be fine.

**Comment by addshore** [comment]
I think it would make much more sense to have this called mediawiki.json or mediawiki-extension.json
As @JeroenDeDauw said this library is not a mediawiki extension!

**Comment by thiemowmde** [comment]
I agree with Jeroen. For actual extensions that do auto-loading its critical and also does make sense to name the file "extension.json". In components that aren't extensions this is (as far as I can see) not necessary and also misleading.

**Comment by filbertkm** [comment]
if extension.json (and treating these as extensions) is not ok, then we should make it so these can be listed under "installed libraries" instead.

**Comment by mariushoch** [comment]
> if extension.json (and treating these as extensions) is not ok, then we should make it so these can be listed under "installed libraries" instead.

Given they're not supposed to be extensions (conceptually), I think that's the way to go, yes.

**Comment by JeroenDeDauw** [comment]
Indeed, it'd be nice if we could finally just remove this MW specific stuff from our libraries. At present not all of them even have this, meaning not all of them are showing up on Special:Version.

**Comment by thiemowmde** [comment]
But this would require a much bigger set of changes, including a change to core's SpecialVersion.php. Currently it's limited to core's vendor/composer/installed.json and can not list libraries that are used by extensions.

I suggest do move forward as suggested: Reduce the PHP entry points to that single wfLoadExtension and move everything else to a extension.json file, but name it mediawiki.json when it is not an actual extension.

**Comment by filbertkm** [comment]
renamed the file to mediawiki-extension.json   we are using the extension registration process. Hopefully  'mediawiki-extension.json' makes that clear enough and clear that it is a mediawiki-specific file.

it still would be good to make SpecialVersion and siteinfo api more flexible to allow putting such library as this in the libraries section. (see https://phabricator.wikimedia.org/T123937)

I realize that for these libraries, we should at least maintain some compatibility with older mediawiki versions. My change works with 1.25+ and if using an older version, then the library is simply not listed in Special:Version, and otherwise the library should still work.

**Comment by JeroenDeDauw** [comment]
> I realize that for these libraries, we should at least maintain some compatibility with older mediawiki versions.

Would be nice. Not sure it's required for this one, though it certainly is for the DV ones used by non-Wikibase MediaWiki extensions.

**Comment by filbertkm** [comment]
@JeroenDeDauw for datavalues, i can include check for wfLoadExtension and if it's older mediawiki, then still use $wgExtensionCredits for as long as we want to support older versions.

for the wikibase libraries, i think 1.25+ is ok for including in Special:Version. If it's older mediawiki, everything else should still work since there is no hard dependency on mediawiki.

**Comment by JeroenDeDauw** [comment]
Sounds good

**Comment by addshore** [comment]
Looks like everyone's concerns have been addressed here.
Also the 1.25+ thing should also be fine too..!

**Comment by thiemowmde** [comment]
For the record: I'm also very happy with this solution, including the function_exists check.

**Pull request merged**
