### PR TITLE
Do not store serialization during deserialization

### PR DESCRIPTION
**Pull request by thiemowmde**
This is a resubmission of #31.

~~[WIP] because tests for the introduced `is_array` checks are missing.~~ **Edit:** The tests are in #70.

[Bug: T98124](https://phabricator.wikimedia.org/T98124)

### CODE REVIEW

**Comment by thiemowmde** [comment]
Rebased.

**Comment by JeroenDeDauw** [comment]
I'm rather dubious about this from a code quality perspective. The decrease in scope of the state is nice in a way, and avoids a class of bugs (which in this case are rather unlikely). However the method complexity is increased, and bugs in the "incorrect ordering of parameters" class become more likely. Not a clear win in either case.

I also do not buy the "might make copies" performance argument given. As far as I can tell, no copies will be made. If PHP where to be stupid about this and not do CoW, then I'd expect more copies to be made with the new code.

While thinking about the later I did realize some performance aspect is improved: the serialization will potentiality go out of memory quicker, depending on how the deserializer is used. One can just unset the field to get around that.

Anyway, I do not object to this change and just want to point out that I do not agree with the provided motivations. +1

**Comment by thiemowmde** [comment]
You are right that the private property probably does not increase any memory footprint. It's just not necessary and confusing when reading and maintaining the code. The serialization simply is not and should not be part of the state of the deserializer object.

**Comment by Benestar** [comment]
o.O What happened here? I just tired to rebase this :S

**Comment by Benestar** [comment]
Lol, I somehow squashed my rebase commit into Thiemo's one and everything's strange now. Should I try to split those two again or can we just merge it as it is?

**Comment by thiemowmde** [comment]
I compared with my local copy of the branch and can not find a mistake. +2 from my side.

**Pull request merged**
