### PR TITLE
Use EntityDocument instead of Entity

### PR DESCRIPTION
**Pull request by JeroenDeDauw**

### CODE REVIEW

**Comment by JeroenDeDauw** [comment]
ScrutinizerCI failure unrelated and fixed by https://github.com/wmde/WikibaseInternalSerialization/pull/52

**Comment by thiemowmde** [comment]
As already discussed in https://github.com/wmde/WikibaseDataModelSerialization/pull/116 I fail to see what the benefit is. The classes are called **Entity** deserializers and are guaranteed to return Entity objects.

I think my recurring confusion is a result of the odd migration path in DataModel.

**Comment by mariushoch** [comment]
+1: Fine with me, but don't want to merge this over Thiemo's comment.

**Comment by thiemowmde** [comment]
My vote is not a -2. The world keeps spinning with this merged.

Will we ever delete `Entity` and rename `EntityDocument` to `Entity`? Or rename `Entity` to `EntityObject` and `EntityDocument` to `Entity`? This would be sooo helpful.

**Comment by JeroenDeDauw** [comment]
@thiemowmde all this commit does is use a more narrow interface. Do you really think it is problematic to merge this?

**Comment by JeroenDeDauw** [comment]
@Benestar @addshore thoughts?

**Comment by thiemowmde** [comment]
Both classes can't give any guarantee because the constructor parameters allow to pass in whatever you want. They are *meant* to return entities (however they are called). But technically there can't be any guarantee given on the return type of the passed in deserializers, and therefore there can't be any guarantee given on the two classes in question in this pull request. Following this argument the only correct return type must be `@return mixed`.

Making the returned type more narrow is going in the right direction because it means making the guarantee given *smaller*. So +1 from my side.

**Comment by Benestar** [comment]
This code contains a lot of really bad assumptions like "if it isn't a property it has to be an item" [[1]](https://github.com/wmde/WikibaseInternalSerialization/blob/master/src/Deserializers/LegacyEntityDeserializer.php#L34)

However, as Entity is deprecated this patch only replaces a deprecated class with the interface we want our users to use in favour of Entity. +2

**Pull request merged**
